<script>
	import demo from '$lib/assets/videos/demo.mp4'
	import Footer from '$lib/ui/Footer.svelte'
	import HomePageNavbar from '$lib/ui/HomePageNavbar.svelte'
</script>

<svelte:head>
	<title>Riju | Create presentations super fast</title>
	<meta
		name="description"
		content="Create presentations in seconds. Riju turns your words into stunning presentations. Our smart tech blends beauty and impact, perfect for impressing clients or inspiring students."
	/>
</svelte:head>

<HomePageNavbar />

<main class="mx-auto max-w-2xl">
	<section class="text-center max-w-2xl mx-auto space-y-14 mt-24 mb-28">
		<hgroup>
			<h1>Create Presentation in Seconds 😎</h1>
			<p>
				Just write content, Riju will convert it into beautiful presentation.
			</p>
		</hgroup>

		<div
			class="flex justify-center gap-3
	"
		>
			<a href="/login" role="button">Create Account</a>
			<a class="secondary outline" href="/dashboard/editor" role="button"
				>Live Demo</a
			>
		</div>
	</section>

	<!-- Cards -->
	<section class="animate__animated animate__fadeIn">
		<article>
			<video class="w-full" src={demo} muted autoplay loop />
			<footer>
				<h2>Saves you hours (Guaranteed)</h2>
				<p>
					You write content; thats all! Riju turns it all into stunning
					presentation(PPT). Our smart tech blends beauty and impact, perfect
					for impressing clients or inspiring students.
				</p>
			</footer>
		</article>
	</section>

	<!-- cards -->
	<section>
		<div class="grid grid-cols-2">
			<article>
				<h3>Super Fast</h3>
				<p>Just write content & select theme generated by AI. That's All..</p>
			</article>
			<article>
				<h3>Beautiful Themes</h3>
				<p>
					Unique AI generated beautiful themes. Now no more same old themes for
					all your presentations.
				</p>
			</article>
		</div>
	</section>

	<!-- cta -->
	<section>
		<hgroup>
			<h2 class="text-center">Don't think. Just do!</h2>
			<h3 class="text-center">(you won't regret it)</h3>
		</hgroup>
		<div class="flex justify-center gap-3">
			<a href="/login" role="button">Create Account</a>
			<a class="secondary outline" href="/dashboard/editor" role="button"
				>Live Demo</a
			>
		</div>
	</section>

	<Footer />
</main>
