create table "public"."presentations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone,
    "title" text,
    "content" jsonb,
    "is_public" boolean default false
);


alter table "public"."presentations" enable row level security;

CREATE UNIQUE INDEX presentations_pkey ON public.presentations USING btree (id, user_id);

alter table "public"."presentations" add constraint "presentations_pkey" PRIMARY KEY using index "presentations_pkey";

alter table "public"."presentations" add constraint "presentations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."presentations" validate constraint "presentations_user_id_fkey";


